package com.mrx.mediaplayerwithlivedata

enum class BROADCAST_CONSTANTS(val value: String) {
    ID("com.mrx.mediaplayerwithbroadcastreceiver"),

    STRING_DATA_TYPE_KEY("STRING_DATA_TYPE_KEY"),
    STRING_DATA_DURATION_KEY("STRING_DATA_DURATION_KEY"),
    STRING_DATA_IS_PLAYING_KEY("STRING_DATA_IS_PLAYING_KEY"),
    NOW_POSITION_TRACK_KEY("NOW_POSITION_TRACK_KEY"),

    SWITCH_STATE("SWITCH_STATE"),
    DURATION_TRACK("DURATION_TRACK"),
    NOW_POSITION_TRACK("NOW_POSITION_TRACK"),
}